FROM node:20-alpine

WORKDIR /app

COPY services/ts-api/package*.json ./
RUN npm install

COPY services/ts-api/tsconfig.json ./
COPY services/ts-api/src ./src
COPY services/ts-api/.env ./

RUN npm run build

COPY services/python-tools/ ./python-tools/
COPY services/python-tools/requirements.txt ./python-tools/requirements.txt

EXPOSE 8080

CMD ["node", "dist/index.js"]
